class CallbackType:
    CREATE_APPLICATION = 'CREATE_APPLICATION'
    APPLICATIONS_STATUS = 'APPLICATIONS_STATUS'
    SECURITY_CONTACTS = 'SECURITY_CONTACTS'
    LOGOUT = 'LOGOUT'

    TAXI = 'TAXI'
    CARRIER = 'CARRIER'
    GUESTS = 'GUESTS'
    PARKING_PROBLEMS = 'PARKING_PROBLEMS'
    OTHER = 'OTHER'
    APPLICATIONS_BACK = 'APPLICATIONS_BACK'
