class CallbackType:
    CREATE_APPLICATION = 'CREATE_APPLICATION'
    APPLICATIONS_STATUS = 'APPLICATIONS_STATUS'
    SECURITY_CONTACTS = 'SECURITY_CONTACTS'
    LOGOUT = 'LOGOUT'

    TAXI = 'TAXI'
    CARRIER = 'CARRIER'
    GUESTS = 'GUESTS'
    PARKING_PROBLEMS = 'PARKING_PROBLEMS'
    OTHER = 'OTHER'
    APPLICATIONS_BACK = 'APPLICATIONS_BACK'

    APPLICATION_PAGINATION_APP = 'APPLICATION_PAGINATION_APP'
    APPLICATIONS_PAGINATION_FORWARD = 'APPLICATIONS_PAGINATION_FORWARD'
    APPLICATIONS_PAGINATION_BACKWARD = 'APPLICATIONS_PAGINATION_BACKWARD'
    APPLICATIONS_PAGINATION_BACK = 'APPLICATIONS_PAGINATION_BACK'

    SINGLE_APPLICATION_BACK = 'SINGLE_APPLICATION_BACK'
    SINGLE_APPLICATION_TO_MAIN = 'SINGLE_APPLICATION_TO_MAIN'

    ADMIN_APPLICATIONS_STATUS = 'ADMIN_APPLICATIONS_STATUS'
    ADMIN_APPLICATION_PAGINATION_APP = 'ADMIN_APPLICATION_PAGINATION_APP'
    ADMIN_APPLICATIONS_PAGINATION_FORWARD = 'ADMIN_APPLICATIONS_PAGINATION_FORWARD'
    ADMIN_APPLICATIONS_PAGINATION_BACKWARD = 'ADMIN_APPLICATIONS_PAGINATION_BACKWARD'
    ADMIN_APPLICATIONS_PAGINATION_BACK = 'ADMIN_APPLICATIONS_PAGINATION_BACK'

    ADMIN_SINGLE_APPLICATION_APPROVE = 'ADMIN_SINGLE_APPLICATION_APPROVE'
    ADMIN_SINGLE_APPLICATION_REJECT = 'ADMIN_SINGLE_APPLICATION_REJECT'
    ADMIN_SINGLE_APPLICATION_BACK = 'ADMIN_SINGLE_APPLICATION_BACK'
    ADMIN_SINGLE_APPLICATION_TO_MAIN = 'ADMIN_SINGLE_APPLICATION_TO_MAIN'


