import enum


class MenuType(enum.Enum):
    START = 'START'

    MAIN = 'MAIN'
    APPLICATIONS = 'APPLICATIONS'
    APPLICATIONS_PAGINATION_MENU = 'APPLICATIONS_PAGINATION_MENU'
    SINGLE_APPLICATION_MENU = 'SINGLE_APPLICATION_MENU'

    ADMIN_SINGLE_APPLICATION_MENU = 'ADMIN_SINGLE_APPLICATION_MENU'
    ADMIN_APPLICATIONS_PAGINATION_MENU = 'ADMIN_APPLICATIONS_PAGINATION_MENU'
    MAIN_ADMIN = 'MAIN_ADMIN'
