import enum


class ButtonCallbackType:
    CREATE_APPLICATION = 'CREATE_APPLICATION'
    APPLICATIONS_STATUS = 'APPLICATIONS_STATUS'
    SECURITY_CONTACTS = 'SECURITY_CONTACTS'
    LOGOUT = 'LOGOUT'
